---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: svc1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc1
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
spec:
  selector:
    matchLabels:
      app: svc1
  replicas: 1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: test
        image: asia-southeast2-docker.pkg.dev/alevz-demo-1/containers/redis2:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: OTEL_TRACES_SAMPLER
            valueFrom:
              configMapKeyRef:
                name: svc1
                key: OTEL_TRACES_SAMPLER
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: svc1
                key: PORT
          - name: WRITEIP
            valueFrom:
              configMapKeyRef:
                name: svc1
                key: WRITEIP
          - name: READIP
            valueFrom:
              configMapKeyRef:
                name: svc1
                key: READIP
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: svc1
data:
  OTEL_TRACES_SAMPLER: 'always_on'
  PORT: '8080'
  WRITEIP: '10.221.0.37'
  READIP: '10.221.0.36'
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  type: LoadBalancer
  selector:
    app: svc1
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: balloon-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balloon
  template:
    metadata:
      labels:
        app: balloon
    spec:
      priorityClassName: balloon-priority
      terminationGracePeriodSeconds: 0
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["infinity"]
        resources:
            requests:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: balloon-priority
value: -10
preemptionPolicy: Never
globalDefault: false
description: "Balloon pod priority."
